repository: yunsur/yunsur.github.io
repository_url: https://github.com/yunsur/yunsur.github.io

title: Bang · Fast and Geek
alias_en: Bang · Fast and Geek
alias_cn: Bang · Fast and Geek
description: A Navigation Website for Yunsur
keywords: Bang, Search, Fast, Geek, Website, Navigation
url: https://yunsur.com
started_at: "2014-12-29"

author: yunsur
author_url: https://yunsur.com
contact: me[at]yunsur[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

analytics:
  google:
    id: UA-74126405-1

timezone: Asia/Shanghai
lang: zh_CN

safe: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tidy

exclude:
  - .gitignore
  - .travis.yml
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - script
  - vendor
