title: 壹页搜索
alias_en: Ys
alias_cn: 壹页搜索
description: 简洁的搜索与导航
keywords: 壹页, 搜索, 快速, 简洁, 导航
url: https://yunsur.com
started_at: "2014-12-29"

author: yunsur
author_url: https://yunsur.com
contact: me[at]yunsur[dot]com

timezone: Asia/Shanghai
lang: zh_CN
charset: UTF-8

safe: false

analytics: 'UA-74126405-1'

compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tidy

exclude:
  - .gitignore
  - .travis.yml
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - script
  - vendor
